export type LevelTrack =
  | "python"
  | "django-basics"
  | "models"
  | "templates-auth"
  | "advanced"
  | "drf"
  | "deploy"
  | "capstone";

export interface LevelTest {
  name: string;
  /** python code that runs after user code to assert, for Pyodide levels */
  assertCode?: string;
  /** expected stdout contains, simple check */
  expectContains?: string[];
  /**
   * expected stdout shows this text EXACTLY this many times.
   * Used by loop missions: printing the line once must not pass a "loop 3 times" task.
   */
  expectCount?: { text: string; times: number }[];
}

/**
 * One labeled piece of the chapter's syntax pattern, e.g. "for" -> "the keyword
 * that starts a loop". Rendered as the TOPIC SYNTAX table so a beginner sees
 * the exact general shape before any real example.
 */
export interface SyntaxPart {
  /** The exact token as it appears in the pattern, e.g. "for" or "range(...)". */
  token: string;
  /** Plain-words meaning of that token in this pattern. */
  meaning: string;
  /** True when the learner replaces this piece with their own value. */
  placeholder?: boolean;
}

export interface GuidedLessonStep {
  title: string;
  body: string;
  /** Tiny runnable snippet for this step. */
  code: string;
  /** Short why-it-works line shown under the snippet. */
  why: string;
}

export interface GuidedLesson {
  /** One-sentence promise of what the learner will truly understand. */
  objective: string;
  steps: GuidedLessonStep[];
  /** One comprehension check the learner answers in their head or in chat. */
  checkQuestion: string;
  checkAnswer: string;
  /** 2-4 sentences cementing the mental model after the mission. */
  takeaways: string[];
  /** Guided Learning label, e.g. "Gemini Guided Learning". */  
  generatedBy: string;
}

export interface Level {
  id: number;
  slug: string;
  title: string;
  track: LevelTrack;
  world: string;
  storyKid: string;
  mission: string;
  analogy10yo: string;
  exampleCode: string;
  /**
   * Line-by-line plain-words explanation of exampleCode, shown right under it.
   * Beginners must never be handed example code nobody decodes for them.
   */
  exampleWalkthrough?: string[];
  /**
   * The topic's generic syntax skeleton, e.g. `for <name> in range(<n>):`.
   * Shown in the TOPIC SYNTAX card as the exact shape to memorize.
   */
  syntaxPattern?: string;
  /** Piece-by-piece explanation of syntaxPattern. */
  syntaxParts?: SyntaxPart[];
  starterCode: string;
  language: "python";
  runnable: boolean; // true = Pyodide can run it (levels 0-7ish)
  tests: LevelTest[];
  rubricForGemini: string;
  hints: string[];
  xp: number;
  boss?: boolean;
  /** True for outline levels whose full content is generated by Gemini on first visit. */
  preview?: boolean;
  /** Core concept keyword the generator focuses on, e.g. "for loops". */
  concept?: string;
  /** The actual syllabus topic this chapter teaches, shown on the map, e.g. "Django Models". */
  topic?: string;
  /** What the learner can build after this topic in the running project, e.g. "Show products on your shop page". */
  projectGoal?: string;
  /** Filled at runtime for generated levels. */
  guidedLesson?: GuidedLesson;
}

export const TRACK_COLORS: Record<LevelTrack, string> = {
  python: "#f2b705",
  "django-basics": "#2f6bff",
  models: "#1f9d55",
  "templates-auth": "#e07b39",
  advanced: "#6d28d9",
  drf: "#d62839",
  deploy: "#0e9f8a",
  capstone: "#191924",
};

export const TRACK_LABEL: Record<LevelTrack, string> = {
  python: "Python Playground",
  "django-basics": "Django Village",
  models: "Model Mountain",
  "templates-auth": "Template Town",
  advanced: "Advanced Forest",
  drf: "DRF Rocket",
  deploy: "Deploy Sky",
  capstone: "Boss: Ship It!",
};

/**
 * Deterministically picks between '/blue.png' and '/yellow.png' for a given chapter/level ID
 * to ensure SSR and client hydration consistency while maintaining a random distribution
 * across all chapters. If no ID is provided, randomly chooses one.
 */
export function getChapterMascot(levelId?: number): string {
  if (levelId === undefined || levelId === null || isNaN(levelId)) {
    return Math.random() < 0.5 ? "/blue.png" : "/yellow.png";
  }
  // Deterministic pseudo-random distribution per chapter to ensure SSR/hydration consistency
  // while appearing random across chapters (mix of blue and yellow)
  const hash = Math.sin((levelId + 1) * 12.9898 + 78.233) * 43758.5453;
  return (hash - Math.floor(hash)) < 0.5 ? "/blue.png" : "/yellow.png";
}
